name: POS API CI

on:
  push:
    branches:
      - "**"
    paths:
      - "api/**"
      - "!.github/**"
      - ".github/api.yaml"
  pull_request:
    branches:
      - main
    paths:
      - "api/**"
      - "!api/**.md"
      - "!.github/**"
      - ".github/api.yaml"

jobs:
  posApi:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.19.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.19.x

      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-api-${{ hashFiles('yarn.lock', 'api/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-api-
            ${{ runner.os }}-yarn-

      - name: Build
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' )
        run: |
          cd api
          rm -rf node_modules
          yarn install --frozen-lockfile --production
          yarn build

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' )
        run: |
          cd api
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t erxes/erxes-pos-api:${GITHUB_REF#refs/heads/} -f Dockerfile .
          docker push erxes/erxes-pos-api:${GITHUB_REF#refs/heads/}
