name: POS UI CI

on:
  push:
    branches:
      - '**'

jobs:
  erxes-pos-ui:
    runs-on: ubuntu-18.04

    # name: Node ${{ matrix.node-version }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 17.2.x
        uses: actions/setup-node@v1
        with:
          node-version: 17.2.x

      - name: Install dependencies
        run: |
          cd ui
          yarn install --frozen-lockfile
          yarn build

      - name: Build docker image
        if: github.event_name == 'push' && (github.ref == 'refs/heads/baterdene' )
        env:
          BASE_IMAGE: erxes/erxes:base-1.18-alpine
        run: |
          cd ui
          echo ${{ secrets.REGISTRY_TOKEN }} | docker login ${{ secrets.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin
          docker build -t ${{ secrets.REGISTRY_URL }}/erxes/erxes-pos-ui:baterdene -f Dockerfile .
          docker push ${{ secrets.REGISTRY_URL }}/erxes/erxes-pos-ui:baterdene
