name: POS UI CI

on:
  push:
    branches:
      - '**'
    paths:
      - 'ui/**'
      - '.github/workflows/ui.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'ui/**'
      - '.github/workflows/ui.yaml'

jobs:
  erxes-pos-ui:
    runs-on: ubuntu-18.04

    # name: Node ${{ matrix.node-version }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js 12.19.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.19.x

      # https://github.com/actions/cache/blob/master/examples.md#node---yarn
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Node.js modules
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-ui-${{ hashFiles('yarn.lock', 'ui/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-ui-${{ hashFiles('ui/**/yarn.lock') }}
            ${{ runner.os }}-yarn-ui-
            ${{ runner.os }}-yarn-

      - name: Build
        run: |
          cd ui
          yarn install --frozen-lockfile --production
          yarn build

      - name: Build docker image
        if: github.event_name == 'push' && ( github.ref == 'refs/heads/main' )
        run: |
          cd ui
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t erxes/erxes-pos-ui:${GITHUB_REF#refs/heads/} -f Dockerfile.dev .
          docker push erxes/erxes-pos-ui:${GITHUB_REF#refs/heads/}
